In [1]:
import torch #그냥 torch로 부른다.
import torchvision # 파이토치에서 vision은 image Processing에 특화된 라이브러리
import torch.nn as nn ## nn은 Neural Net
import numpy as np
import torchvision.transforms as transforms      #transforms....data augmentation

### Create Tensor ... Generating Neural Net

In [2]:
x = torch.tensor(1., requires_grad = True)
w = torch.tensor(2., requires_grad = True)
b = torch.tensor(3., requires_grad = True)

# w*x + b
print(x)
print(w)
print(b)

tensor(1., requires_grad=True)
tensor(2., requires_grad=True)
tensor(3., requires_grad=True)


In [3]:
y = w*x + b    #1차원.. y=2x +3 ....

y.backward()
print(x.grad)
print(w.grad)
print(b.grad)

tensor(2.)
tensor(1.)
tensor(1.)


### Create Tensor... 2차원

In [4]:
x = torch.randn(10,3)
y = torch.randn(10,2)
x, y



(tensor([[ 0.2911,  1.7956,  2.1875],
         [-0.9275, -0.0997, -1.7818],
         [ 2.9039,  0.8946, -1.7575],
         [ 0.8788, -1.4106, -0.5224],
         [ 1.2568,  0.4833, -0.9598],
         [-2.3983,  0.6421, -1.0771],
         [ 0.8562,  0.5754,  1.8065],
         [-1.5659, -0.2798,  0.6609],
         [ 0.9884, -0.8721,  2.5218],
         [-0.7326, -0.5411,  1.0354]]),
 tensor([[-0.6684,  0.1992],
         [ 1.6893,  0.5388],
         [ 0.7811,  0.0507],
         [-0.6806,  1.1849],
         [ 0.3092,  0.2249],
         [-0.4171,  0.2391],
         [-1.1460,  1.0156],
         [ 0.4053, -0.8443],
         [-1.0312,  0.4714],
         [ 0.2972,  0.4472]]))

In [5]:
linear = nn.Linear(3,2)          #neural net 모델 만듦 
print('Weight', linear.weight)
print('Bias', linear.bias)

print(linear.parameters())

Weight Parameter containing:
tensor([[-0.4045,  0.0854, -0.4350],
        [ 0.1138, -0.0155, -0.2817]], requires_grad=True)
Bias Parameter containing:
tensor([-0.4667, -0.3858], requires_grad=True)
<generator object Module.parameters at 0x000002D4E17E73C8>


In [6]:
#선정의해둔다
loss_function = nn.MSELoss()      # 미리 loss 함수를 정의해두고 사용은 밑에서(나중에).... MSELoss

'''
인자값으로 linear 모델에서 학습시키고자 하는 주체를 넣어준다
linear.parameters()
parameters()는 weight, bias값을 내포하고 있는 해킹된 함수
'''
optimizer = torch.optim.SGD(linear.parameters(), lr = 0.01)         #어떤방식으로 산을내려갈지 정해줌


pred = linear.forward(x)    #(모델에 x를 입력하면 예측값이 나온다.)

loss = loss_function(pred, y)

print('loss before Backpropagation ::', loss.item())

loss.backward()

print('dL/dw : ', linear.weight.grad)
print('dL/db : ', linear.bias.grad)

optimizer.step()    #이때 수정된 값으로 실질적인 학습....하강한다....

# 반복효과
pred = linear(x)
loss = loss_function(pred, y)
print('Loss.... after backpropagation::', loss.item())

loss before Backpropagation :: 1.0006486177444458
dL/dw :  tensor([[-0.8164, -0.0698, -0.2351],
        [-0.0983,  0.0420, -0.8912]])
dL/db :  tensor([-0.5652, -0.7823])
Loss.... after backpropagation:: 0.9762647151947021


#### Neural Net Flow
    1. 모델 정의 
    2. 모델에 값 입력해서 예측값 할당
    3. Loss
    4. Backward()
    5. 학습진행 step()